# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distributed.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64istributed.proto\"\x1e\n\x0eTrafficRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"5\n\x0fTrafficResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\ntime_stamp\x18\x02 \x01(\x01\")\n\nResRequest\x12\x0c\n\x04uids\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"\x1d\n\x0bResResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1e\n\x0eProfileRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"5\n\x0fProfileResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\ntime_stamp\x18\x02 \x01(\x01\"\x1e\n\x0eNetProcRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"5\n\x0fNetProcResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\ntime_stamp\x18\x02 \x01(\x01\x32\xd4\x01\n\x0bGrpcService\x12\x32\n\x0bget_traffic\x12\x0f.TrafficRequest\x1a\x10.TrafficResponse\"\x00\x12(\n\tadjustRes\x12\x0b.ResRequest\x1a\x0c.ResResponse\"\x00\x12\x32\n\x0bget_profile\x12\x0f.ProfileRequest\x1a\x10.ProfileResponse\"\x00\x12\x33\n\x0cget_net_proc\x12\x0f.NetProcRequest\x1a\x10.NetProcResponse\"\x00\x42\x03\x80\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distributed_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\001'
  _TRAFFICREQUEST._serialized_start=21
  _TRAFFICREQUEST._serialized_end=51
  _TRAFFICRESPONSE._serialized_start=53
  _TRAFFICRESPONSE._serialized_end=106
  _RESREQUEST._serialized_start=108
  _RESREQUEST._serialized_end=149
  _RESRESPONSE._serialized_start=151
  _RESRESPONSE._serialized_end=180
  _PROFILEREQUEST._serialized_start=182
  _PROFILEREQUEST._serialized_end=212
  _PROFILERESPONSE._serialized_start=214
  _PROFILERESPONSE._serialized_end=267
  _NETPROCREQUEST._serialized_start=269
  _NETPROCREQUEST._serialized_end=299
  _NETPROCRESPONSE._serialized_start=301
  _NETPROCRESPONSE._serialized_end=354
  _GRPCSERVICE._serialized_start=357
  _GRPCSERVICE._serialized_end=569
# @@protoc_insertion_point(module_scope)
