apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-history
  name: mongodb-history
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-history
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-history
    spec:
      nodeName: cpu-07
      containers:
        - image: mongo
          imagePullPolicy: IfNotPresent
          name: hotel-reserv-history-mongo
          ports:
            - containerPort: 27017
          #resources:
          #  requests:
          #    cpu: "200m"
          #  limits:
          #    cpu: "200m"
      hostname: history-db
      restartPolicy: Always
status: {}
